name: Actualización de Datos

on:
  schedule:
    - cron: '0 8,13,18 * * 1-5'  # Ejecutar a las 8 AM, 1 PM y 6 PM, de lunes a viernes
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ajusta la versión según tu configuración de Vite

      - name: Install Dependencies
        run: npm install

      - name: Ejecutar Actualización de Datos
        run: node ./src/data/update-data.js

      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ENVIROMENT_DOS }}
          BRANCH_NAME: 'main'
