name: Verificar Secrets

on:
  push:
    branches:
      - main

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar PAT_PRUEBA
        run: echo "El valor de PAT_PRUEBA es ${{ secrets.PAT_PRUEBA }}"
