name: Verificar Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    env:
      SUPER_SECRET: ${{ secrets.PAT_PRUEBA2 }}

    steps:
      - name: Verificar PAT_PRUEBA2
        run: echo "El valor de SUPER_SECRET es $SUPER_SECRET"

