name: Verificar Permisos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: Verificar Clonación
        run: |
          git clone https://${{ secrets.PAT_PRUEBA }}@github.com/johnray000/pruebas-vite3.git
          cd pruebas-vite3
          git pull

      - name: Limpiar
        run: |
          cd ..
          rm -rf pruebas-vite3
